# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 620)
        MainWindow.setMinimumSize(QtCore.QSize(750, 620))
        MainWindow.setMaximumSize(QtCore.QSize(750, 620))
        MainWindow.setStyleSheet("background: url(C:/Users/Vano/PycharmProjects/final_project/UI/background.png)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.middle_groupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.middle_groupbox.setGeometry(QtCore.QRect(10, 150, 731, 261))
        self.middle_groupbox.setStyleSheet("QGroupBox#middle_groupbox:disabled {\n"
"    background-color : rgba(255, 255, 255, 10)\n"
"}")
        self.middle_groupbox.setTitle("")
        self.middle_groupbox.setObjectName("middle_groupbox")
        self.formLayoutWidget = QtWidgets.QWidget(self.middle_groupbox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 731, 261))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.formLayoutWidget.setFont(font)
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setObjectName("formLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_dbs = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_dbs.setFont(font)
        self.btn_dbs.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_dbs.setStyleSheet("QPushButton#btn_dbs{\n"
"background-color: #007bff;\n"
"color: white;\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: #007bff;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton#btn_dbs:pressed {\n"
"    border-style: inset;\n"
"}\n"
"")
        self.btn_dbs.setObjectName("btn_dbs")
        self.horizontalLayout.addWidget(self.btn_dbs)
        self.btn_programming = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_programming.setFont(font)
        self.btn_programming.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_programming.setStyleSheet("QPushButton#btn_programming{\n"
"background-color: #6c757d;\n"
"color: white;\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: #6c757d;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton#btn_programming:pressed {\n"
"    border-style: inset;\n"
"}")
        self.btn_programming.setObjectName("btn_programming")
        self.horizontalLayout.addWidget(self.btn_programming)
        self.btn_salary = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_salary.setFont(font)
        self.btn_salary.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_salary.setStyleSheet("QPushButton#btn_salary{\n"
"background-color: #28a745;\n"
"color: white;\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: #28a745;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton#btn_salary:pressed {\n"
"    border-style: inset;\n"
"}\n"
"")
        self.btn_salary.setObjectName("btn_salary")
        self.horizontalLayout.addWidget(self.btn_salary)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background: none;\n"
"color: white;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.lab_name = QtWidgets.QLabel(self.formLayoutWidget)
        self.lab_name.setStyleSheet("color: white;\n"
"background:none;\n"
"font-size: 15px;")
        self.lab_name.setObjectName("lab_name")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lab_name)
        self.text_name = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.text_name.setMaximumSize(QtCore.QSize(16777215, 25))
        self.text_name.setStyleSheet("color: white;\n"
"font-size: 12px;")
        self.text_name.setObjectName("text_name")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.text_name)
        self.lab_surname = QtWidgets.QLabel(self.formLayoutWidget)
        self.lab_surname.setStyleSheet("color: white;\n"
"background:none;\n"
"font-size: 15px;")
        self.lab_surname.setObjectName("lab_surname")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lab_surname)
        self.text_surname = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.text_surname.setMaximumSize(QtCore.QSize(16777215, 25))
        self.text_surname.setStyleSheet("color: white;\n"
"font-size: 12px;")
        self.text_surname.setObjectName("text_surname")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.text_surname)
        self.lab_iban = QtWidgets.QLabel(self.formLayoutWidget)
        self.lab_iban.setStyleSheet("color: white;\n"
"background:none;\n"
"font-size: 15px;")
        self.lab_iban.setObjectName("lab_iban")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lab_iban)
        self.text_iban = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.text_iban.setMaximumSize(QtCore.QSize(16777215, 25))
        self.text_iban.setStyleSheet("color: white;\n"
"font-size: 12px;")
        self.text_iban.setObjectName("text_iban")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.text_iban)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setStyleSheet("color: white;\n"
"background:none;\n"
"font-size: 15px;")
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.text_money = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.text_money.setStyleSheet("color: white;\n"
"font-size:14px;")
        self.text_money.setMinimum(1)
        self.text_money.setObjectName("text_money")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.text_money)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.formLayout_2)
        self.btn_donate = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_donate.setFont(font)
        self.btn_donate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_donate.setStyleSheet("QPushButton#btn_donate{\n"
"background-color: #e0a800;\n"
"color: white;\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: #e0a800;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton#btn_donate:pressed {\n"
"    border-style: inset;\n"
"}\n"
"")
        self.btn_donate.setObjectName("btn_donate")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.btn_donate)
        self.bottom_groupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.bottom_groupbox.setGeometry(QtCore.QRect(10, 430, 731, 91))
        self.bottom_groupbox.setStyleSheet("QGroupBox#bottom_groupbox:disabled {\n"
"background-color : rgba(0, 0, 0, 60)\n"
"}")
        self.bottom_groupbox.setTitle("")
        self.bottom_groupbox.setObjectName("bottom_groupbox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.bottom_groupbox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 731, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.verticalLayoutWidget_2.setFont(font)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: white;\n"
"background: none;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_txt = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_txt.setFont(font)
        self.btn_txt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_txt.setStyleSheet("color: white;")
        self.btn_txt.setObjectName("btn_txt")
        self.horizontalLayout_2.addWidget(self.btn_txt)
        self.btn_csv = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_csv.setFont(font)
        self.btn_csv.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_csv.setStyleSheet("color: white;")
        self.btn_csv.setObjectName("btn_csv")
        self.horizontalLayout_2.addWidget(self.btn_csv)
        self.btn_xlsx = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_xlsx.setFont(font)
        self.btn_xlsx.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_xlsx.setStyleSheet("color: white;")
        self.btn_xlsx.setObjectName("btn_xlsx")
        self.horizontalLayout_2.addWidget(self.btn_xlsx)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.top_groupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.top_groupbox.setGeometry(QtCore.QRect(10, 40, 731, 101))
        self.top_groupbox.setStyleSheet("QGroupBox#top_groupbox:disabled {\n"
"background-color : rgba(0, 0, 0, 60)\n"
"}")
        self.top_groupbox.setTitle("")
        self.top_groupbox.setObjectName("top_groupbox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.top_groupbox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 731, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.verticalLayoutWidget.setFont(font)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_upload = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_upload.setFont(font)
        self.btn_upload.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_upload.setStyleSheet("QPushButton#btn_upload{\n"
"background-color:#17a2b8;\n"
"color: white;\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: #17a2b8;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton#btn_upload:pressed {\n"
"    border-style: inset;\n"
"}")
        self.btn_upload.setObjectName("btn_upload")
        self.horizontalLayout_3.addWidget(self.btn_upload)
        self.quantity = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.quantity.setFont(font)
        self.quantity.setStyleSheet("color: white;")
        self.quantity.setAlignment(QtCore.Qt.AlignCenter)
        self.quantity.setObjectName("quantity")
        self.horizontalLayout_3.addWidget(self.quantity)
        self.btn_delete_all = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_delete_all.setFont(font)
        self.btn_delete_all.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_delete_all.setStyleSheet("QPushButton#btn_delete_all{\n"
"background-color: #dc3545;\n"
"color: white;\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: #dc3545;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton#btn_delete_all:pressed {\n"
"    border-style: inset;\n"
"}")
        self.btn_delete_all.setObjectName("btn_delete_all")
        self.horizontalLayout_3.addWidget(self.btn_delete_all)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setStyleSheet("padding: 10px;\n"
"color: white;\n"
"background: #555;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.heading = QtWidgets.QLabel(self.centralwidget)
        self.heading.setEnabled(True)
        self.heading.setGeometry(QtCore.QRect(10, 0, 731, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.heading.setFont(font)
        self.heading.setStyleSheet("color: white;\n"
"background: none;")
        self.heading.setAlignment(QtCore.Qt.AlignCenter)
        self.heading.setObjectName("heading")
        self.error_msg = QtWidgets.QLabel(self.centralwidget)
        self.error_msg.setGeometry(QtCore.QRect(80, 540, 611, 51))
        self.error_msg.setStyleSheet("font-size: 17px;\n"
"color: white;\n"
"background: #dc3545;\n"
"border-radius: 10px;")
        self.error_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.error_msg.setObjectName("error_msg")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_dbs.setText(_translate("MainWindow", "მონაცემთა ბაზები"))
        self.btn_programming.setText(_translate("MainWindow", "პროგრამული, სკრიპტინგ და markup ენები"))
        self.btn_salary.setText(_translate("MainWindow", "ანაზღაურება-ასაკი"))
        self.label.setText(_translate("MainWindow", "Donate"))
        self.lab_name.setText(_translate("MainWindow", "სახელი"))
        self.lab_surname.setText(_translate("MainWindow", "გვარი"))
        self.lab_iban.setText(_translate("MainWindow", "ანგარიშის ნომერი"))
        self.label_6.setText(_translate("MainWindow", "თანხა:"))
        self.btn_donate.setText(_translate("MainWindow", "Donate"))
        self.label_5.setText(_translate("MainWindow", "მონაცემების ჩამოტვირთვა"))
        self.btn_txt.setText(_translate("MainWindow", ".txt ფაილი"))
        self.btn_csv.setText(_translate("MainWindow", ".csv ფაილი"))
        self.btn_xlsx.setText(_translate("MainWindow", ".xlsx ფაილი"))
        self.btn_upload.setText(_translate("MainWindow", "მონაცემების ჩატვირთვა"))
        self.quantity.setText(_translate("MainWindow", "სულ ბაზაშია: 65000 ჩანაწერი"))
        self.btn_delete_all.setText(_translate("MainWindow", "მონაცემების წაშლა"))
        self.comboBox.setItemText(0, _translate("MainWindow", "ტექნოლოგიები"))
        self.comboBox.setItemText(1, _translate("MainWindow", "მონაცემები"))
        self.heading.setText(_translate("MainWindow", "2020 - Developer Survey"))
        self.error_msg.setText(_translate("MainWindow", "Error, Something Went Wrong"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
